application: wenzeltech-landstream
version: 1
runtime: python
api_version: 1
threadsafe: false

builtins:
- deferred: on



handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  
  
- url: /static
  static_dir: static
  
  
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  expiration: '1d'
    
- url: /.*
  script: uploadTest.py
  
